// Generated by schema/generate-entity-refs.mjs from schema/entity-refs.json —
// never hand-edited. The one list of entity-reference fields
// (spec/world.md "Identity"); js/test/entity-refs.test.mjs fails when
// this copy drifts from the canonical file.
/** @type {{scope: string, path: string[], kind: "bindable"|"id"}[]} */
export const ENTITY_REFS = [
  {
    "scope": "entity",
    "path": [
      "behaviors",
      "*",
      "LookAt",
      "target"
    ],
    "kind": "bindable"
  },
  {
    "scope": "entity",
    "path": [
      "behaviors",
      "*",
      "Orbit",
      "center"
    ],
    "kind": "bindable"
  },
  {
    "scope": "entity",
    "path": [
      "parent"
    ],
    "kind": "bindable"
  },
  {
    "scope": "avatar",
    "path": [
      "model_entity"
    ],
    "kind": "bindable"
  },
  {
    "scope": "creation",
    "path": [
      "entities",
      "*"
    ],
    "kind": "id"
  }
];
