// The one list of entity-reference fields (spec/world.md "Identity",
// schema/entity-refs.json): every field that holds an entity reference,
// marked `x-entity-ref` in the schema. Name binding, merge rewriting
// and ingestion validation read this list instead of hand-written ones,
// so the format gaining a reference field is one marker, seen by all
// five references — not five lists drifting apart.
//
// This is an embedded copy of the canonical generated file: a published
// package can't read the repo's schema/ at runtime, and the drift test
// (EntityRefsTests) fails when this table and schema/entity-refs.json
// disagree. Never hand-edited past a schema change.

import Foundation

/// One marked entity-reference field.
///
/// - `scope`: the object `path` walks from — an entity (or its patch,
///   the same fields), the manifest's avatar, or one creation in
///   `creations[]`.
/// - `path`: the key sequence to the field; `"*"` walks every array
///   element.
/// - `kind`: `"bindable"` — a name is accepted at intake and MUST bind
///   to an id at ingestion; `"id"` — numeric only.
public struct EntityRef: Equatable, Sendable {
    public var scope: String
    public var path: [String]
    public var kind: String

    public init(scope: String, path: [String], kind: String) {
        self.scope = scope
        self.path = path
        self.kind = kind
    }
}

/// The marked refs, mirroring schema/entity-refs.json's `refs` array
/// exactly (generated by schema/generate-entity-refs.mjs from
/// world.schema.json's x-entity-ref markers).
public let ENTITY_REFS: [EntityRef] = [
    EntityRef(scope: "entity", path: ["behaviors", "*", "LookAt", "target"], kind: "bindable"),
    EntityRef(scope: "entity", path: ["behaviors", "*", "Orbit", "center"], kind: "bindable"),
    EntityRef(scope: "entity", path: ["parent"], kind: "bindable"),
    EntityRef(scope: "avatar", path: ["model_entity"], kind: "bindable"),
    EntityRef(scope: "creation", path: ["entities", "*"], kind: "id"),
]

/// The marked refs of one scope (and optionally one kind).
func refsOf(_ scope: String, kind: String? = nil) -> [EntityRef] {
    ENTITY_REFS.filter { $0.scope == scope && (kind == nil || $0.kind == kind!) }
}

/// Walk a marked path, calling `fn` at the leaf with the field's value
/// in-out; `"*"` walks every array element. Missing keys walk to
/// nothing.
func walkRefPath(
    _ node: inout JSONValue,
    _ path: [String],
    _ i: Int,
    _ fn: (inout JSONValue) throws -> Void
) rethrows {
    let key = path[i]
    let last = i == path.count - 1
    if key == "*" {
        guard case .array(var elements) = node else { return }
        for j in elements.indices {
            if last { try fn(&elements[j]) }
            else { try walkRefPath(&elements[j], path, i + 1, fn) }
        }
        node = .array(elements)
        return
    }
    guard case .object(var object) = node, var child = object[key] else { return }
    if last { try fn(&child) }
    else { try walkRefPath(&child, path, i + 1, fn) }
    object[key] = child
    node = .object(object)
}

/// Every marked entity-reference field of `value` — an entity or patch
/// (`"entity"`), the manifest's avatar (`"avatar"`), one creation
/// (`"creation"`) — calling `fn` on each, in place.
func eachRef(
    _ scope: String,
    _ value: inout JSONValue,
    _ fn: (inout JSONValue) throws -> Void
) rethrows {
    for ref in refsOf(scope) {
        try walkRefPath(&value, ref.path, 0, fn)
    }
}
