// The one list of entity-reference fields (spec/world.md "Identity",
// schema/entity-refs.json, generated by generate-entity-refs.mjs from
// the normative schema's x-entity-ref markers): name binding, merge
// rewriting and validation read this list instead of hand-written
// ones. This file is the package's embedded copy — a published
// package can't read the repo's schema/ at runtime — plus the walker
// the passes share. EntityRefsTests fails when the copy drifts from
// the canonical file.

package org.openworldformat

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

/** What a reference field holds — the schema's `x-entity-ref` marker. */
enum class EntityRefKind(val marker: String) {
    /** A name is accepted at intake and MUST bind to an id at ingestion. */
    BINDABLE("bindable"),

    /** Numeric only. */
    ID("id"),
}

/**
 * One marked entity-reference field. [scope] names the object [path]
 * walks from: an entity (or its patch — the same fields), the
 * manifest's avatar, or one creation in `creations[]`. `"*"` in a path
 * walks every array element.
 */
data class EntityRef(
    val scope: String,
    val path: List<String>,
    val kind: EntityRefKind,
)

/** The embedded copy of schema/entity-refs.json's `refs`, in the
 *  canonical file's order — hand-written here, drift-tested there. */
val ENTITY_REFS: List<EntityRef> = listOf(
    EntityRef("entity", listOf("behaviors", "*", "LookAt", "target"), EntityRefKind.BINDABLE),
    EntityRef("entity", listOf("behaviors", "*", "Orbit", "center"), EntityRefKind.BINDABLE),
    EntityRef("entity", listOf("parent"), EntityRefKind.BINDABLE),
    EntityRef("avatar", listOf("model_entity"), EntityRefKind.BINDABLE),
    EntityRef("creation", listOf("entities", "*"), EntityRefKind.ID),
)

/** The marked refs of one scope (and optionally one kind). */
internal fun refsOf(scope: String, kind: EntityRefKind? = null): List<EntityRef> =
    ENTITY_REFS.filter { it.scope == scope && (kind == null || it.kind == kind) }

/**
 * Walk a marked path, returning the tree with `fn` applied at each
 * leaf; `"*"` walks every array element. Missing keys walk to nothing
 * — the tree comes back as-is. JsonElement trees are immutable, so the
 * walk rebuilds, and only the branches a leaf actually changed.
 */
internal fun walkRefPath(
    node: JsonElement,
    path: List<String>,
    i: Int,
    fn: (JsonElement) -> JsonElement,
): JsonElement {
    val key = path[i]
    val last = i == path.size - 1
    if (key == "*") {
        val arr = node.arr ?: return node
        var changed = false
        val out = arr.map { element ->
            val next = if (last) fn(element) else walkRefPath(element, path, i + 1, fn)
            if (next !== element) changed = true
            next
        }
        return if (changed) JsonArray(out) else node
    }
    val obj = node.obj ?: return node
    val current = obj[key] ?: return node
    val next = if (last) fn(current) else walkRefPath(current, path, i + 1, fn)
    if (next === current) return node
    return JsonObject(obj.toMutableMap().apply { put(key, next) })
}

/**
 * Every marked entity-reference field of [value] in [scope] — an
 * entity or patch ("entity"), the manifest's avatar ("avatar"), one
 * creation ("creation") — with `fn` applied at each, in tree order.
 */
internal fun eachRef(
    scope: String,
    value: JsonElement,
    fn: (JsonElement) -> JsonElement,
): JsonElement {
    var out = value
    for (ref in refsOf(scope)) out = walkRefPath(out, ref.path, 0, fn)
    return out
}
